# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20151214_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('finality', models.CharField(max_length=255)),
                ('who', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=255)),
                ('ffile', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255)),
                ('language_plugin', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Proyect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('languages', models.ManyToManyField(to='users.LanguageConfig')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('given', models.CharField(max_length=255)),
                ('then', models.CharField(max_length=255)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Feature')),
            ],
        ),
        migrations.CreateModel(
            name='SenderConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='scenario',
            name='tags',
            field=models.ManyToManyField(to='users.Tag'),
        ),
        migrations.AddField(
            model_name='feature',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.LanguageConfig'),
        ),
        migrations.AddField(
            model_name='feature',
            name='proyect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Proyect'),
        ),
    ]
