# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_remove_project_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='And',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('related_to', models.CharField(choices=[('given', 'given'), ('then', 'then'), ('when', 'when')], max_length=255)),
                ('table', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('finality', models.CharField(max_length=255)),
                ('who', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=255)),
                ('ffile', models.FileField(upload_to='')),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='bdd.Background')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.LanguageConfig')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Given',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('background', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='givens', to='bdd.Background')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='bdd.Feature')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='users.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Then',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thens', to='bdd.Scenario')),
            ],
        ),
        migrations.CreateModel(
            name='When',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whens', to='bdd.Scenario')),
            ],
        ),
        migrations.AddField(
            model_name='given',
            name='scenario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='givens', to='bdd.Scenario'),
        ),
        migrations.AddField(
            model_name='and',
            name='background',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bdd.Background'),
        ),
        migrations.AddField(
            model_name='and',
            name='scenario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bdd.Scenario'),
        ),
    ]
